# Site settings
title: Workshop on single-cell/nuclei RNA sequencing data analysis using nf-core/scflow

theme: jekyll-theme-minimal
authour: MAP Team

domain: scflow-workshop2024.github.io
url: https://nfancy.github.io/scflow-workshop2024.github.io/
baseurl: ""

plugins:
  - jekyll-last-modified-at

last-modified-at:
    date-format: '%d-%b-%y'
