# Site settings
title: nf-core/scflow workshop 2024

theme: jekyll-theme-minimal
authour: MAP Team

domain: scflow-workshop2024.github.io
url: https://scflow-workshop2024.github.io/
baseurl: ""

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-last-modified-at

last-modified-at:
    date-format: '%d-%b-%y'
